export const strings = {
    language: "Мова",
    leaveFeedback: "Залишити відгук",
    supportProject: "Підтримати проект",
    faq: "ЧаПи",
    advices: "Поради",
    termsConditions: "Умови використання",
    privacyPolicy: "Політика конфіденційності",
    clearCache: "Очистити кеш",
    signout: "Вийти",
    scheme: "Схема",
    more: "Більше",
    less: "Менше",
    locale: "uk-UA",
    profieTab: "Профіль",
    ukrainian: "Українська",
    kacapian: "російська",
    seriouslyQuestion: "Серйозно?",
    noRussianMessage: "Хіба схоже, що тут буде російська?",
    fixMistake: "Виправити помилку",
    getSweatOrDie: "Потій або помри ©OTOY",
    close: "Закрити",
    search: "Пошук",
    categories: "Категорії",
    oopsSomethingLost: "Упс, схоже, щось загубилось...",
    cancel: "Скасувати",
    allCacheWillBeDeletedMessage: "Усі дані, що зберегаються локально буде видалено"
}